# Generated by Django 5.0.4 on 2024-05-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="qr",
            name="img_url",
        ),
        migrations.AddField(
            model_name="qr",
            name="image",
            field=models.ImageField(
                blank=True, default="../../static/assets/bg-image.png", upload_to=""
            ),
        ),
    ]
