# Generated by Django 5.0.4 on 2024-05-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr", "0002_remove_qr_img_url_qr_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="qr",
            name="image",
            field=models.ImageField(blank=True, default="fallback.png", upload_to=""),
        ),
    ]
