# Generated by Django 5.0.4 on 2024-05-15 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("qr", "0003_alter_qr_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="qr",
            name="url",
            field=models.URLField(null=True),
        ),
    ]
